package namvn.project2.parkwar.controller;

import namvn.project2.parkwar.model.TaiKhoan;
import namvn.project2.parkwar.repository.TaiKhoanRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class TaiKhoanController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TaiKhoanRepository taiKhoanRepository;

//    @PostMapping(path="/login") // Map ONLY GET Requests
//    @ResponseStatus(HttpStatus.OK)
//    public @ResponseBody boolean login (@RequestBody TaiKhoan taiKhoan) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        TaiKhoan tkTemp=taiKhoanRepository.findTaiKhoanByTentkAndMatKhau(taiKhoan);
//        if(tkTemp!=null)
//            return true;
//        return false;
//    }servlet
@GetMapping(path = "/add")
    public @ResponseBody
String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        TaiKhoan n = new TaiKhoan();
        n.setTentk(name);
        n.setMatKhau(email);
        taiKhoanRepository.save(n);
        return "Saved12";
    }
}
